### PR TITLE
86 flashcard images

### LINKED ISSUE #86: F.7 Add image to flashcard
## Tasks
- Add an image template to a card that shows when an image url is provided
- Access images from database
- Make sure image is resized to fit the card

### PR DESCRIPTION
**Pull request by B-Yamawaki**
fixes #86 

- All flashcards (basic, view, edit/create) all have the ability to display images if the image is in the flashcard data
- Images are properly scaled to fit the cards
- I uploaded a couple of images of various sizes to the project and put their paths on the cards of some of the lemonade flashcard set in the json db
- I also made sure that if the text of flashcards gets too long, it does not mess with the image.
  - For now, when the text for the descriptions exceed the size of the cards, a scroll bar appears. This can be changed later.
- I separated the style sheet for the flashcard component

## Note
- The uploading, downloading, and caching of images will come in #27, but this will likely be split in to two tasks later one for the dev service and one for the firebase service

flashcard_w_image
image
image

### CODE REVIEW

**Comment by ashkjones** [comment]
I am not a fan of the scrolling within the flashcards.
image

Could you set a `maxlength` on the definition `text-area` element to prevent extra-long definitions? You might need to play around with different lengths to see what works best for our UI.
https://github.com/PonderTeam/ponder-app/blob/66b0cda603185fa19a0d6151a746105c12e36cd3/src/app/flashcard-editor/flashcard-editor.component.html#L29-L38

I think limiting the length of definitions is also helpful for enforcing the user uses good flashcard studying habits. To quote Andy Matuschak, a software engineer in the EduTech space: 
>>Retrieval practice prompts should be focused. A question or answer involving too much detail will dull your concentration and stimulate incomplete retrievals, leaving some bulbs unlit. Unfocused questions also make it harder to check whether you remembered all parts of the answer and to note places where you differed. It’s usually best to focus on one detail at a time.

**Comment by B-Yamawaki** [comment]
Branch is ready for re-review

**Comment by ashkjones** [comment]
Please remove the flip icon and the shadow on the cards.
image

**Comment by ashkjones** [comment]
Can you add some kind of indictor that shows that the editor box has a character limit?
image

**Comment by ashkjones** [comment]
Also, I didn't do a formal review because I don't have time to look at everything right now. I just wanted to provide feedback asap

**Comment by B-Yamawaki** [comment]
> Also, I didn't do a formal review because I don't have time to look at everything right now. I just wanted to provide feedback asap

Thank you, I will make those changes.

**Comment by B-Yamawaki** [comment]
Changes made. The code still needs to be reviewed.

**Review by iamdylanhuynh001 — APPROVED** [review]
Looked through all the files changes, and I don't see anything that needs coding style changes.

Also not sure why "npm install" wasn't working, but I had to do "npm install --save typesense" to install typesense.  Might wanna discuss about that.

**Pull request merged**
